[package]
name = "file_lookup"
version = "0.1.1"
edition = "2021"
description = "Simple functions to search up in the file tree for a file by name."
license = "MIT"

[dependencies]
dirs = "5.0.0"
log = "0.4.17"
